name: catatan_harian
description: "Aplikasi untuk pencatatan harian kegiatan pekerja atau non pekerja."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  adaptive_responsive_util: ^1.0.3
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  group_button: ^5.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.1
  jiffy: ^6.3.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  logger: ^2.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.2
  upgrader: ^10.3.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

# flutter_launcher_icons:
#   android: "launcher_icon"
#   image_path: "assets/images/logo_icon_ika.png"
#   min_sdk_android: 21
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/development/.env
    - assets/staging/.env
    - assets/production/.env

flutter_gen:
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
